name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        GOOS: ['windows', 'linux', 'darwin']
        include:
          - GOOS: windows
            GOARCH: amd64
          - GOOS: linux
            GOARCH: amd64
          - GOOS: darwin
            GOARCH: arm64
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          check-latest: true
      - name: build project
        id: build
        run: |
          mkdir -p bin
          make all
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: ${{ matrix.GOOS }}
          path: bin/*-${{ matrix.GOOS }}
