name: release

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  release:
    name: release
    needs: ["test", "build"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: get version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          patchList: "fix, bugfix, test, doc"
          minorList: "feat, refactor"
          noVersionBumpBehavior: "patch"
          noNewCommitBehavior: "warn"

      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true


      - name: draft release
        id: draft
        if: steps.semver.outputs.next != ''
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ github.token }}
          allowUpdates: true
          draft: false
          prerelease: true
          commit: ${{ github.sha }}
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          body: "pending"
          artifacts: 'dist/*'

      - name: update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}

      - name: deploy release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ github.token }}
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          artifactErrorsFailBuild: true
          artifacts: 'dist/*'

      - name: commit CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v3
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
